module.exports.descriptors = [
    'Himalayan',
    'Sacred',
    'Shanti',
    'Ganga',
    'Tranquil',
    'Verdant',
    'Misty',
    'Evergreen',
    'Aravalli',
    'Deodar',
    'Peepal',
    'Lotus',
    'Saffron',
    'Kailash',
    'Teesta',
    'Brahmaputra',
    'Kanchenjunga',
    'Sundari',
    'Nilgiri'
];

module.exports.places = [
    'Ghats',
    'Ashram',
    'Valley',
    'Meadow',
    'Sangam',
    'Mela Grounds',
    'Mangroves',
    'Sanctuary',
    'Backwaters',
    'Riverside',
    'Dhaam',
    'Bazaar',
    'Tea Estate',
    'Char Dham',
    'Wildlife Reserve',
    'Gompa',
    'Dzong',
    'Stepwell',
    'Hilltop',
    'Plateau'
];
